# Generated by Django 5.2.1 on 2025-05-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='places_json',
            field=models.TextField(default='[]'),
        ),
    ]
