# Generated by Django 5.2.1 on 2025-05-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_places_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
