# Generated by Django 5.2.5 on 2025-08-19 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_categorie_voiture_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='cooperative',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='chauffeurs', to='reservation.cooperative'),
            preserve_default=False,
        ),
    ]
