# Generated by Django 5.2.5 on 2025-08-19 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_chauffeur_cooperative'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='cooperative',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='reservation.cooperative'),
            preserve_default=False,
        ),
    ]
