# Generated by Django 5.2.5 on 2025-09-16 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_reservation_nom_client_reservation_prenom_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Manifold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('cin', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_famille', models.CharField(max_length=15)),
                ('numero_utilisateur', models.CharField(max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
            ],
        ),
    ]
