# Generated by Django 5.2.5 on 2025-09-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_chauffeur_photo_manifold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifold',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
    ]
