# Generated by Django 5.2.5 on 2025-09-16 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_manifold_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifold',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='manifold',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='manifold',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='manifold',
            name='numero_famille',
        ),
        migrations.RemoveField(
            model_name='manifold',
            name='numero_utilisateur',
        ),
        migrations.RemoveField(
            model_name='manifold',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='manifold',
            name='reservation',
        ),
        migrations.AddField(
            model_name='manifold',
            name='trajet',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='reservation.trajet'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('cin', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_famille', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_utilisateur', models.CharField(blank=True, max_length=15, null=True)),
                ('nb_places', models.PositiveIntegerField(default=1)),
                ('manifold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passagers', to='reservation.manifold')),
            ],
        ),
    ]
