# Generated by Django 5.2.5 on 2025-09-24 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_remove_manifold_cin_remove_manifold_date_naissance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passager',
            old_name='nb_places',
            new_name='numero_places',
        ),
    ]
