# Generated by Django 5.2.5 on 2025-11-16 03:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_rename_nb_places_passager_numero_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.png', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
